websitecoffeechoice/Models/GioHang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websitecoffeechoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int maGioHang { get; set; }
        public Nullable<long> maSanPham { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<int> maNguoiDung { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}

websitecoffeechoice/Controllers/GioHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using websitecoffeechoice.Models;
namespace websitecoffeechoice.Controllers
{
    public class GioHangController : Controller
    {
        // GET: GioHang
        CafeDBEntities webcf = new CafeDBEntities();
        public ActionResult Index()
        {
            return View((List<CartModel>)Session["cart"]);
        }
        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.MaSP.Equals(id))
                    return i;
            return -1;
        }
        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = webcf.SanPham.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = webcf.SanPham.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.MaSP == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
    }
}

websitecoffeechoice/Controllers/ThanhToanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using websitecoffeechoice.Models;


namespace websitecoffeechoice.Controllers
{
    public class ThanhToanController : Controller
    {
        // GET: ThanhToan
        CafeDBEntities webcf = new CafeDBEntities();//tao doi tuong kieu du lieu cua database
        public ActionResult Index()
        {
            if (Session["MaND"] == null)
            {
                return RedirectToAction("DangNhap","Home");
            }
            else
            {

                //Lay thong tin tu gio hang tu bien session
                var lstGioHang = (List<CartModel>)Session["cart"];
                //gan du lieu cho hoa don
                HoaDon hd = new HoaDon();
                hd.Ten = "DonHang-" + DateTime.Now.ToString("yyyy-MM-dd-HH-mm-ss");
                hd.MaND = int.Parse(Session["MaND"].ToString());
                hd.NgayBan = DateTime.Now;

               
                //lay ID vua tao de luu vao bang GioHang
                int GioHangid = hd.MaHD;
              
                List<GioHang> ListGioHang = new List<GioHang>();

               
                      HoaDon hoadon = new HoaDon();
                foreach (var item in lstGioHang)
                {
                    GioHang gh = new GioHang();
                    

                    gh.soLuong = item.Quantity;
                    gh.maGioHang = GioHangid;
                    gh.maSanPham = item.Product.MaSP;
                     gh.maNguoiDung = hd.MaND;
                    gh.TongTien = item.Quantity * item.Product.Gia;
                    hoadon.TongTien = gh.TongTien; 
                    ListGioHang.Add(gh);
                }
                hd.TongTien = hoadon.TongTien;

                 webcf.HoaDon.Add(hd);

                //luu thong tin vao bang hoa don
                webcf.SaveChanges();

                webcf.GioHang.AddRange(ListGioHang);
                webcf.SaveChanges();
            }

            return View();
        }
    }
}

websitecoffeechoice/Views/GioHang/Index.cshtml
@model IEnumerable<websitecoffeechoice.Models.CartModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        // hàm xử lý sự kiện click vào phần tử có id là "removecart". Khi người dùng nhấp vào phần tử đó, hàm xử lý sự kiện này sẽ được thực thi.
        $("#removecart").click(function () {
            var model = {};//tạo biến tên model 
            //lấy id sản phẩm ở hàng remove 
            model.id = $("#productid").val();//id có thể đổi được ,Gán giá trị của phần tử có id là "productid" vào thuộc tính "id" của đối tượng "model


            $.ajax({
                type: "POST",//Xác định phương thức HTTP được sử dụng là POST.
                url: '@Url.Action("Remove", "GioHang")',//tới controller giohang và thực hiện hàm remove 
                data: JSON.stringify(model),//Chuyển đối tượng "model" thành chuỗi JSON và gửi nó dưới dạng dữ liệu yêu cầu.
                dataType: "json",//Xác định kiểu dữ liệu mong đợi nhận lại từ phản hồi của yêu cầu là JSON.
                contentType: "application/json; charset=utf-8",//Xác định kiểu dữ liệu của dữ liệu yêu cầu là JSON.
                success: function () {

                    $('#CartCount').text(@Session["count"] - 1);
                    $("#product-" + model.id).remove();
                },
                error: function () {
                    alert("Lỗi trong khi thêm vào giỏ hàng!");
                }
            });
            return false;
        });
    });
</script>

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">

        <div class="row">
            <main class="col-md-9">
                <div class="card">

                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Sản phẩm</th>
                                <th scope="col" width="120">Số lượng</th>
                                <th scope="col" width="120">Giá</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)

                                {
                                    <tr id="product-@item.Product.MaSP">
                                        <td>
                                            <figure class="itemside">
                                                <div class="aside"><img src="~/Content/images/items/@item.Product.Anh" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="#" class="title text-dark">@item.Product.TenSP</a>

                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <input type="text"   value="@item.Quantity" />
                                            
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">@item.Product.Gia VNĐ</var>

                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td class="text-right">
                                            <input type="hidden" value="@item.Product.MaSP" id="productid" /><!--#productid khai báo trên javascript -->
                                            <!--removecart là biến dùng trong đoạn javascript ở trên-->
                                            <a href="" class="btn btn-light" id="removecart"> Xóa sản phẩm</a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <p>Không có sản phẩm trong giỏ hàng!</p>
                            }


                        </tbody>
                    </table>

                    <div class="card-body border-top">
                        <a href="@Url.Action("Index","ThanhToan")" class="btn btn-primary float-md-right"> Thanh Toán > <i class="fa fa-chevron-right"></i> </a>
                        <a href="@Url.Action("Index","Home")" class="btn btn-light"> <i class="fa fa-chevron-left"></i>< Tiếp tục mua sắm! </a>
                    </div>
                </div> <!-- card.// -->

                <div class="alert alert-success mt-3">
                    <p class="icontext"><i class="icon text-success fa fa-truck"></i> Free Delivery within 1-2 weeks</p>
                </div>

            </main> <!-- col.// -->

        </div>

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->